### ISSUE TITLE
Signing up for lab sections should be mutually exclusive

### ISSUE THREAD

**Issue by nsandell123** [gt-scheduler/website#121]
**To Reproduce**
1. Go to scheduler
2. Add CS 3001 to your schedule. 
3. Add Multiple Lab Sections (ex: A01 and A08)
![image](https://user-images.githubusercontent.com/24736875/140687604-980a90f5-d167-42cd-84e1-ea6306b7ae9a.png)

**Expected behavior**
I expected choosing another lab section to deselect the lab section that was already selected.

**Comment by ananay22** [comment]
I don't think this should be a bug. I personally put in a bunch of lab sections on the same schedule to see which ones fit where, and then start removing them manually till I find the one that I want. Given that you have to select both the class and the lab from the same dropdown, it also makes sense to have more than 1 selection in a dropdown. 
I think this should stay the way that it is

**Comment by nsandell123** [comment]
That makes sense.
