### ISSUE TITLE
Cannot read location with hover 

### ISSUE THREAD

**Issue by Jenny1998** [gt-scheduler/website#132]
**The feature**
Give a clear 2-3 sentence description of your feature here.
Would like to see the full location, including room number when hovered over. 
**Detailed explanation**
Elaborate on your initial description of the feature, including its components.
Now I've to manually expand the width of my browser to see the full location 
**Mockups**
If available, include design mockups or examples of similar features in existing products that others can use as reference.
This is the current view: 
<img width="688" alt="image" src="https://user-images.githubusercontent.com/27874152/186203658-1170badc-2dcf-4f7b-8d3b-b036feb8077f.png">

Expanded view: 
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/27874152/186203773-0789a9b0-eb74-4622-b1f6-1b15a4128524.png">

Expected view: 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/27874152/186203984-04bce5b2-de81-4734-b8e5-a6d7f4495d5b.png">

**Additional context**

**Comment by jazeved0** [comment]
This was implemented in #144
