### ISSUE TITLE
Show class location and professor in mobile site

### ISSUE THREAD

**Issue by amitkulk123** [gt-scheduler/website#133]
**The feature**
Show the class location and professor on the "Courses" and/or "Calendar" section on the mobile site (specifically any device with a horizontal resolution <1024px). If the text is too long to display fully and exceeds the height of the box, then there should be an option to click on the box to open up some sort of dialog box where we can then see the class location and professor. 

**Detailed explanation**
I'm not able to see the class location and professor in the mobile site. It seems like this information is hidden with `display: none` since having this information displayed can sometimes exceed the height of the box (in which the height is based on the duration of the class). 

Although there is already a map view where we can see the general building of where the class takes place, having this location information displayed would be useful since students often need to know the exact room number and location of the class from their phone while commuting. 

**Additional context**
Here's how it looks on desktop:
<img width="259" alt="Screen Shot 2022-08-23 at 8 50 36 PM" src="https://user-images.githubusercontent.com/9218849/186299594-46d36817-b708-479c-8dd4-38f989c57e1b.png">

Here's how it looks on mobile:
<img width="73" alt="Screen Shot 2022-08-23 at 8 50 25 PM" src="https://user-images.githubusercontent.com/9218849/186299676-c133fca6-1840-4057-8071-4b5c08855057.png">

**Comment by jazeved0** [comment]
This was implemented in #144
