### ISSUE TITLE
Update Course Combination Algorithm

### ISSUE THREAD

**Issue by nhatnghiho** [gt-scheduler/website#151]
### Description
We need to update the algorithm that generates course combinations so that it does not generate combinations that conflict with the recurring events. This function is called `getCombinations` and you can find it under `src/data/beans/Oscar.ts`.

### Acceptance Criteria
- [x] Generated combinations do not conflict with the events.
- [x] Update `getCombinations`'s usage in `CourseContainer`.

### Other Notes

I'd recommend passing a new parameter `events` (type `Event`) into `getCombinations` and use this parameter to exclude combinations that conflict with the events. I don't expect any changes should be made to the return values with this approach, but let me know if you disagree!

**Comment by samarth52** [comment]
Issue completed with #155
