### ISSUE TITLE
Add “Create a Copy of the Schedule” Feature

### ISSUE THREAD

**Issue by suhyun-yun** [gt-scheduler/website#177]
### Description

![Image](https://user-images.githubusercontent.com/70905798/221701392-8c8f6b80-e4ab-4872-83b9-cedfaa865a94.png)

*The button (in red) is supposed to create a duplicate copy of the selected schedule named `Create a Copy`. Right now it doesn't appear to do anything*

### Acceptance Criteria
- [ ] Upon clicking the `Create a Copy` button, a new schedule should be generated in the list of schedules below the current schedule.
    - [ ] The name of the new schedule should be "OriginalScheduleName" + " (1)"
    - [ ] Upon the nth click of the `Create a Copy` button, each new schedule created should have a name of "OriginalScheduleName" + " (n)"
- [ ] `ScheduleContext` and local storage/firebase collection must be updated with the new schedule.
- [ ] The view should be switched to the duplicate schedule, not the original one.
- [ ] Make sure the above feature is functional in mobile view and web view

**Comment by sophiazlin** [comment]
This bug only occurs if you are signed in. If you are not signed in, the button works fine.

**Comment by nhatnghiho** [comment]
Closed as resolved in #193.
