### ISSUE TITLE
Add Feature Title Preview Labels Upon Hover

### ISSUE THREAD

**Issue by suhyun-yun** [gt-scheduler/website#178]
### Description

![Image](https://user-images.githubusercontent.com/70905798/221853204-f4cfaa66-8613-4d73-b8a5-885c2ec8c9b5.png)

*hovering over any of the above icons does not display the name of the feature*

![Image](https://user-images.githubusercontent.com/70905798/221853235-cf002f5d-a0bc-4ec1-a477-3789ec4145cb.png)

*hovering over the icon should display the preview box like the above “exclude from combinations” box*

![Image](https://user-images.githubusercontent.com/70905798/221853267-f1e57045-472e-41b8-a4a3-e5abc69ab921.png)

*reference of the preview box*

Hovering over each of the icon should display the respective feature title to better visibility of our preexisting features:
Box 1:
- Rename Schedule
- Create a copy
- Delete Schedule

Box 2:
- View Sections and Waitlists
- Prerequisites
- Course Color
- Delete Course

### Acceptance Criteria
- [ ] Make sure buttons for each schedule display preview text box with text upon hover
  - [ ] Make sure hovering over `Rename Schedule` button displays preview text box with text "Rename Schedule"
  - [ ] Make sure hovering over `Create a Copy of Schedule` button displays preview text box with text "Create a Copy"
  - [ ] Make sure hovering over `Delete Schedule` button displays preview text box with text "Delete Schedule"
- [ ] Make sure buttons for each course display preview text box with text upon hover
  - [ ] Make sure hovering over `Down Arrow to Expand` button displays preview text box with text "View Sections and Waitlists"
  - [ ] Make sure hovering over `Prerequisites` button displays preview text box with text "Prerequisites"
  - [ ] Make sure hovering over `Course Color` button displays preview text box with text "Course Color"
  - [ ] Make sure hovering over `Delete Course` button displays preview text box with text "Delete Course"
    

### Other Notes

```

**Comment by nhatnghiho** [comment]
Closed as resolved in #195.
