### ISSUE TITLE
Fix Feedback Window Close Button

### ISSUE THREAD

**Issue by suhyun-yun** [gt-scheduler/website#180]
### Description

![Image](https://user-images.githubusercontent.com/70905798/221854402-aed673ad-f541-43eb-afc9-e7816e3a158a.png)
*screen after submitting feedback from the bottom right corner of the main screen*

Ideally, the x button on the top right should close the window, and the close button on the bottom center should end the submission session. However, upon clicking close and reopening the feedback button, the screen does not reset but rather remains to keep the above screen.

### Acceptance Criteria
- [x] Make sure the x button on the top right closes the session window 
- [x] Make sure that the close button on the bottom center ends the session and closes the session window
    - [x] Upon reopening the feedback window after the close button, make sure a new session starts

**Comment by nhatnghiho** [comment]
Closed as resolved in #198
