### ISSUE TITLE
Fix Delete Schedule Display Message

### ISSUE THREAD

**Issue by suhyun-yun** [gt-scheduler/website#181]
### Description
![Image](https://user-images.githubusercontent.com/70905798/221951486-26609ada-6679-40d2-8364-3097486093a8.png)
*Upon clicking the delete button, the message of the popup changes to “Are you sure you want to delete schedule <unknown>?” for a split second before the popup is closed and course schedule is deleted*

### Acceptance Criteria
- [x] “Are you sure you want to delete schedule <unknown>?” message is investigated and removed.
- [x] Popup should be closed immediately with no further UI changes.

**Comment by nhatnghiho** [comment]
Closed as resolved in #202
