### ISSUE TITLE
Add text to display Saturday + Async Classes

### ISSUE THREAD

**Issue by suhyun-yun** [gt-scheduler/website#188]
### Description

Online and non-Atlanta sections tend to be TBA (i.e., having no start and end times on Oscar) and are not displayed on the calendar. Saturday classes, in the mean time, break the calendar and should thus be hidden. As a result, we want to add a text description for hidden sections at the bottom of the calendar.

![Image](https://user-images.githubusercontent.com/70905798/222790560-5db44824-d681-405f-95a6-0012e86d7f72.png)

### Acceptance Criteria
- [x] The bottom text is displayed with all TBA and weekend sections. Each section must include the course name + the section code.
- [x] When a user exports the calendar via downloading the image, the text should also display in the exported image.
- [x] The text should be available in appropriate ratio (text should not be cut off)
  - [x] The text should be wrapped (moved to the next line) or scrollable automatically according to screen size
- [x] Mobile view works.

**Comment by nhatnghiho** [comment]
Closed as resolved in #196
