### ISSUE TITLE
Add 2023-08 Finals Matrix

### ISSUE THREAD

**Issue by blaketenantwatson** [gt-scheduler/website#248]
### Problem Description

Manually add the Fall 2023 Finals matrix to `matrix.json` in the crawler repository

### Your Goal
- Only a single line of code needs to be added with the following:
```
"202308": "https://registrar.gatech.edu/public/files/202308-Final-Exam-Matrix.pdf"
```

**Comment by nhatnghiho** [comment]
Resolved in gt-scheduler/crawler-v2/pull/20
