### ISSUE TITLE
[BoG S24] Special Topics Prerequisites and Titles

### ISSUE THREAD

**Issue by yatharth-b** [gt-scheduler/website#267]
### Problem Description

Currently GTS is unable to display the titles and prerequisites of special topics courses like CS 8803 (each section is a different course). Some work has already been done on this - https://github.com/gt-scheduler/website/pull/245, but we would like to also add the functionality to display prerequisites for the different sections. For example, ECON 4803 has different prereqs for every section.

### Your Goal
- Understand crawler codebase
- Investigate API endpoints to get prerequisites for indvidual sections
- Update crawler output accordingly

**Comment by aeluro1** [comment]
Status update: backend changes complete at PR https://github.com/gt-scheduler/crawler-v2/pull/28
