### ISSUE TITLE
TypeError while constructing courseDateMap in Map component

### ISSUE THREAD

**Issue by jazevedo620** [gt-scheduler/website#40]
When [building the `courseDateMap` data structure](https://github.com/gt-scheduler/website/blob/df44a957751c91cceb7ad5fd6cd43eec103ec37a/src/components/Map/index.js#L27) within the `Map` component, it's possible for the map to not contain the desired day, in which case the array will be `undefined` and invoking `push` on it will result in a `TypeError`. It's unclear what the underlying reason/steps to reproduce for this are.

A simple solution would be to ignore any days that don't exist in the [`courseDateMap`](https://github.com/gt-scheduler/website/blob/development/src/components/Map/index.js#L13). Additionally, further investigation may be warranted into the conditions that cause this error to happen.

### Related Sentry issue (Private)

(Must be logged in to view; only maintainers have access.)

https://sentry.io/organizations/gt-scheduler/issues/2307136753/

### Estimated user impact

Sentry errors have been logged for **4 users** in the issue linked above.

**Comment by JustinH11235** [comment]
This might already be known but there are some classes that are Saturday/Sunday, which afaik isn't handled at all in the code (I know at least they show up weirdly on calendar). I would think this would cause a lot of issues, possibly the one mentioned in this issue.

**Comment by jazevedo620** [comment]
TODO manually verify that this is fixed, investigate Saturday/Sunday courses

**Comment by jazevedo620** [comment]
This is fixed, but Saturday/Sunday classes are still an edge case with various parts of the scheduler. Opening a separate issue to track this.
