### ISSUE TITLE
Daily schedule on map tab incorrectly sorts classes by time

### ISSUE THREAD

**Issue by gtwillwin** [gt-scheduler/website#45]
In certain cases (when a class begins between noon and one pm) it is incorrectly placed at the bottom of the list, which is otherwise sorted by time. Attached pictures display the problem.

![firefox_i4RdmCfF4L](https://user-images.githubusercontent.com/7633229/129425120-1b72eaae-1da1-4526-8464-17c8864525c3.png)
![firefox_83uRJWAsh5](https://user-images.githubusercontent.com/7633229/129425122-496c91f7-839e-4b88-b7a0-0830d53b8e70.png)
![firefox_AKX9adtDgW](https://user-images.githubusercontent.com/7633229/129425123-05169990-1a3b-46a8-ba03-c44339a85e86.png)

**Comment by jazevedo620** [comment]
Hi, if you don't mind, could you link the CRNs or Course ID + Section (like "CS 1331 B1") that you used to reproduce the issue (just so that it's easier to test)?

Thanks for reporting this bug!
